# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1f968ee40b3244caea4119b5162a12230c18693a396ed8aa487411d086b17f7c8a3809ea01bb8a013e3bfd20b702fe1f989e292cdfadc840e2cad62f5f106d

test:
  secret_key_base: dce386a3dfce4372cb740273eb479374383716db61a8ab76972484766a0f68df42f8d4b0468233dea35211b4da7f5dc26de67eb8393537cfd101a0d2591e8ccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
